#!/usr/bin/env zsh

ssh-keygen -t ed25519 -C "191619059+zslobodan@users.noreply.github.com" -f ~/.ssh/id_ed25519

eval "$(ssh-agent -s)"

touch ~/.ssh/config

echo -e "Host *\n  AddKeysToAgent yes\n  IdentityFile ~/.ssh/id_ed25519" | tee ~/.ssh/config

ssh-add ~/.ssh/id_ed25519

if command -v pbcopy &> /dev/null; then
  pbcopy < ~/.ssh/id_ed25519.pub
elif command -v xclip &> /dev/null; then
  xclip -sel clip < ~/.ssh/id_ed25519.pub
else
  echo "No clipboard utility found. Please copy the public key manually."
  cat ~/.ssh/id_ed25519.pub
fi

echo "SSH key has been generated and copied to clipboard."
